### ISSUE TITLE
Extra parentheses on a remote function capture &Mongo.object_id()/0 have been deprecated. Please remove the parentheses: &Mongo.object_id/0

### ISSUE THREAD

**Issue by phanmn** [zookzook/yildun#1]
Thank you for your library

**Comment by zookzook** [comment]
Could you provide some more information?

**Comment by phanmn** [comment]
- I have to replace `&Mongo.object_id()/0` to `&Mongo.object_id/0` in source code to remove warning.
- Here is my commit https://github.com/phanmn/yildun/commit/5bd0c7dc0b537123d06414b4db99e846afdb57c1

**Comment by zookzook** [comment]
Maybe you can provide a Pull-Request, so I can merge it and we release a new version?

**Comment by Tossmann** [comment]
First of all, thanks for providing this library. I've used the latest version 0.1.1 and still receive the deprecation warning mentioned in here.

When downloading the the 0.1.1 source code I can see that the changes made have not been included. Would you (@zookzook) mind release a version with the fixed deprecation warning. Would appreciate it!

**Comment by zookzook** [comment]
I published a new version 0.1.2, that should fix the warnings.
