### ISSUE TITLE
Map with embedded structs

### ISSUE THREAD

**Issue by sarat1669** [zookzook/yildun#5]
Can maps be supported?

```elixir
{:map, String.t(), Connection}
```

Where key is a string and value is Connection struct

**Comment by zookzook** [comment]
Yes, it does, but you need to write your own dump/load function to support the map. Checks the documentation or look at [board.ex](https://github.com/zookzook/vega/blob/0577024afc734933048645976705784512fbc1f4/lib/vega/board.ex#L927) or [issue.ex](https://github.com/zookzook/vega/blob/0577024afc734933048645976705784512fbc1f4/lib/vega/issue/issue.ex#L30) as an example.
